language: python
dist: xenial
python:
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get install apache2 apache2-dev
  - sudo apt-get install python3-dev
  - sudo apt-get install libssl-dev libcurl4-openssl-dev
  - sudo apt-get install mysql-server libmysqlclient-dev
# command to install dependencies
install: pip install -r requirements/local.txt
# command to setup database
before_script:
  - mysql -u root -e "CREATE DATABASE chris_dev CHARACTER SET utf8;"
  - mysql -u root -e "GRANT ALL ON chris_dev.* TO 'chris'@'localhost' IDENTIFIED BY 'Chris1234';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'chris'@'localhost';"
  - cd chris_backend
  - python manage.py migrate
# command to run tests
script: python manage.py test
notifications:
  slack: fnndsc:gGPIVAOtMikWomA1EKrVYIjO
