apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chris
  template:
    metadata:
      labels:
        name: chris
    spec:
      containers:
      - name: chris
        image: fnndsc/chris:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: cube-config
        - secretRef:
            name: cube-secrets